# Makefile for Borland C 3.1

CC = tcc
FLAGS = -ml

all: pixel.exe lines.exe rect.exe circle.exe bitmap.exe palette.exe mouse.exe unchain.exe modes.exe

pixel.exe: pixel.c
	$(CC) $(FLAGS) pixel.c

lines.exe: lines.c
	$(CC) $(FLAGS) lines.c

rect.exe: rect.c
	$(CC) $(FLAGS) rect.c

circle.exe: circle.c
	$(CC) $(FLAGS) circle.c

bitmap.exe: bitmap.c
	$(CC) $(FLAGS) bitmap.c

palette.exe: palette.c
	$(CC) $(FLAGS) palette.c

mouse.exe: mouse.c
	$(CC) $(FLAGS) mouse.c

unchain.exe: unchain.c
	$(CC) $(FLAGS) unchain.c

modes.exe: modes.c
	$(CC) $(FLAGS) modes.c
